### ISSUE TITLE
Crash running under anaconda

### ISSUE THREAD

**Issue by alejandrojapkin** [KaroDievas/car-sound-classification-with-keras#2]
$ python predictor.py 

Using TensorFlow backend.
Traceback (most recent call last):
  File "predictor.py", line 21, in <module>
    model.add(MaxPooling2D(pool_size=(2, 2)))
  File "/Users/pato/anaconda/lib/python2.7/site-packages/keras/models.py", line 332, in add
    output_tensor = layer(self.outputs[0])
  File "/Users/pato/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 572, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/Users/pato/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 635, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/Users/pato/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 166, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/Users/pato/anaconda/lib/python2.7/site-packages/keras/layers/pooling.py", line 160, in call
    dim_ordering=self.dim_ordering)
  File "/Users/pato/anaconda/lib/python2.7/site-packages/keras/layers/pooling.py", line 210, in _pooling_function
    pool_mode='max')
  File "/Users/pato/anaconda/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2866, in pool2d
    x = tf.nn.max_pool(x, pool_size, strides, padding=padding)
  File "/Users/pato/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1793, in max_pool
    name=name)
  File "/Users/pato/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1598, in _max_pool
    data_format=data_format, name=name)
  File "/Users/pato/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/Users/pato/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2397, in create_op
    set_shapes_for_outputs(ret)
  File "/Users/pato/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1757, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/Users/pato/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1707, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/Users/pato/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/Users/pato/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Negative dimension size caused by subtracting 2 from 1 for 'MaxPool' (op: 'MaxPool') with input shapes: [?,1,254,32].

**Comment by KaroDievas** [comment]
I never try it with anaconda, but just keep in mind, that predictor.py you should edit with correct paths to model weights, training data and data which you are trying to predict. Also there should be aligned pictures dimensions with model weight if you are using precompiled weights.

**Comment by alejandrojapkin** [comment]
I have pointed it to the data supplied in your trunk. Can you provide a full step by step usage example so that I can test it? It is not clear what the system actually does, nor what does it predicts and how.

**Comment by KaroDievas** [comment]
I have made so updated to the code and documentation.
But bassically if you want to test it with yours data, you should  first get about 50 spectra images of your car engine sound (with wavelet sound explorer). Then train it. And then you can predict. Because this project idea is not to detect cars brand but to detect concreate car. Also this source can not right predict if in audio stream hearing more than one car engine.

How I generate spectra analysis pictures:
- recording car engine sound about one minute (converts it to wav)
- then with audacity divide whole stream into 400ms.
- each 400ms of audio passed to wavelet sound explorer (if can not hold more longer record:( )
- when generated images cutted with snipping tool and placed to his representative class
- when run training with image_classificator_more_layers.py
- when run predictor.py whitch uses in training step generates weight and pass picture which should be non used in network training

Is this an example which you expected ? :)

**Comment by alejandrojapkin** [comment]
Let's review this

- Split a wav into 400ms chunks.
- Batch process each chunk through a power spectrum analysis. You mention "wavelet sound explorer" which is the spectrum visualization for Audacity, but what about others? And what specific configurations for that Audacity plugin do you use??
- I don't understand what "representative class means" or what snipping tool you're talking about. My guess is that you crop and resize the images using a certain criteria and that criteria is not clear to me.
- Run the training image classificator how exactly?
- Run the predictor how exactly? What is the expected output? Just a log with weights?

**Comment by KaroDievas** [comment]
- wavelet sound explorer - there is link in readme.md file. 
- Audacity I use only for getting 400ms chunks and thats it. 
- Snipping tool is the default windows tool. When I get power spectrum analysis picture, I just capture screen view with that tool. There is no any rezising criteria.

Also I updated that readme.md (there is writen how to run training, expected output and how run predictor) and some sources. Also added comments in important rows. Please review it.
